version: '3.6'

networks:
  daisuki:
    external: true

services:
  daisuki-pgloader:
    image: pgloader
    restart: "no"
    networks:
      - daisuki
    command:
      - pgloader
      - mysql://root:${MARIADB_ROOT_PASSWORD}@daisuki-mariadb:3306/kpop
      - postgresql://postgres:${POSTGRES_PASSWORD}@daisuki-pg:5432/kpop
