version: '3.6'

networks:
  daisuki:
    external: true

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5444:5432
    networks:
      - daisuki
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kpop
  graphql-engine:
    image: hasura/graphql-engine:v2.8.3
    depends_on:
      postgres:
        condition: service_started
    restart: always
    networks:
      - daisuki
    ports:
      - 8999:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/kpop
      HASURA_GRAPHQL_ADMIN_SECRET: hello123
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'