version: '3.6'

networks:
  daisuki:
    external: true

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5444:5432
    networks:
      - daisuki
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kpop
