table:
  schema: kpop
  name: app_kpop
configuration:
  custom_root_fields:
    select_by_pk: kpop_track
  custom_name: kpop_tracks
  column_config: {}
  custom_column_names: {}
object_relationships:
  - name: artist
    using:
      manual_configuration:
        remote_table:
          schema: kpop
          name: app_kpop_group
        insertion_order: null
        column_mapping:
          id_artist: id
remote_relationships:
  - definition:
      to_source:
        relationship_type: array
        source: default
        table:
          schema: rpd
          name: parts
        field_mapping:
          vlink: youtube_id
    name: rpd_parts
select_permissions:
  - role: user
    permission:
      columns:
        - awards
        - dislikes
        - id
        - id_artist
        - id_original_artist
        - id_parent
        - likes
        - recentlikes
        - recentviews
        - views
        - kname
        - name
        - name_aka
        - original_name
        - regionlocked
        - tags
        - vlink
        - releasedate
        - lastupdate
        - publishedon
        - vtype
      filter: {}
